### PR TITLE
https://issues.jboss.org/browse/SEAMSECURITY-98

### PR DESCRIPTION
**Pull request by nheron**
Hi,
here should be a good version
Thanks
Nicolas Héron

### CODE REVIEW

**Comment by lincolnthree** [comment]
Thanks! Rhis PR looks perfect. 

Just so I know, why is it necessary to set the user in this manner? (Just want to understand fully.)

**Comment by nheron** [comment]
Hi,
according to https://community.jboss.org/thread/206645?tstart=0,
after login we have to set a user name, which is not done (according to the error message).
in the source code
according to the sourse code (in the javax.security)  i get the issue here:

358         activeAuthenticator.postAuthenticate();
359
360         if (!activeAuthenticator.getStatus().equals(AuthenticationStatus.SUCCESS)) return;
361
362         user = activeAuthenticator.getUser();
363
364         if (user == null)
365         {
366            throw new AuthenticationException("Authenticator must provide a non-null User after successful authentication");
367         }

So the conclusion was to set the user name :) But is is in the thread (https://community.jboss.org/message/764701#764701)
When will you apply the pull request ?
Thanks
Nicolas

**Comment by lincolnthree** [comment]
Looks good. Thank you!

**Comment by lincolnthree** [comment]
Thanks for the explanation.

**Comment by lincolnthree** [comment]
Released.

On Mon, Jan 7, 2013 at 1:11 PM, Nicolas Héron notifications@github.comwrote:

> Hi,
> according to https://community.jboss.org/thread/206645?tstart=0,
> after login we have to set a user name, which is not done (according to
> the error message).
> in the source code
> according to the sourse code (in the javax.security) i get the issue here:
> 
> 358 activeAuthenticator.postAuthenticate();
> 359
> 360 if
> (!activeAuthenticator.getStatus().equals(AuthenticationStatus.SUCCESS))
> return;
> 361
> 362 user = activeAuthenticator.getUser();
> 363
> 364 if (user == null)
> 365 {
> 366 throw new AuthenticationException("Authenticator must provide a
> non-null User after successful authentication");
> 367 }
> 
> So the conclusion was to set the user name :) But is is in the thread (
> https://community.jboss.org/message/764701#764701)
> When will you apply the pull request ?
> Thanks
> Nicolas
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seam/security/pull/46#issuecomment-11963091.

## 

Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Pull request merged**
